Using Bootstrap
rida-elbahtouri/-Bootstrap-project pull request #1
Opened 2020-06-01 14:28 UTC by rida-elbahtouri

<h1>Using Bootstrap</h1>

#### What does this PR do?
created a Newsweek website clone based on Bootstrap 4

### in this project I :

- created a new HTML document.

- Think about all the elements on the page and how they are grouped together.

- Add Bootstrap to the project

- Layout the basic structure of the page using empty semantic HTML elements that are appropriately sized and which are positioned by using the appropriate Bootstrap classes.

- Set up the top title and navigation bar.

#### How should this be manually tested?
just clone the project and open the index.html file

2020-06-01 23:33 UTC, addod19 commented
## Pull Request under review by Daniel Larbi Addo (TSE)

2020-06-01 23:35 UTC, addod19 requested changes
## Status: Require changes :recycle: :traffic_light: 

Hi @rida-elbahtouri, great job with this project :+1: Excellent commit messages :100: PR professional, very descriptive. Great job :slightly_smiling_face: Great use of bootstrap classes. Let us improve our project and make it even better. Kindly address the comments below, so we can approve the project.
- Kindly visit stickler-ci.com so we can enable stickler to check for CSS file
- In the ```Nav``` we are missing the ```current date``` and the main navigations links
``` Clone ```
![nav](https://user-images.githubusercontent.com/46388113/83463630-1c7c2300-a45e-11ea-867a-0e4e3b0153cf.png)
``` Source ```
![nav1](https://user-images.githubusercontent.com/46388113/83463657-37e72e00-a45e-11ea-8aff-c1742408d599.png)
- We are currently missing the ``` latest news section ``` and ``` the featured slideshow ```
![ln](https://user-images.githubusercontent.com/46388113/83463921-e4291480-a45e-11ea-8571-75d518b35abb.png)
![fet](https://user-images.githubusercontent.com/46388113/83464057-44b85180-a45f-11ea-84fb-e5b86b022b06.png)
- Kindly fix the broken live link in the README file

Kindly make these changes and submit another code review :+1: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2020-06-02 09:12 UTC, rida-elbahtouri commented
Thank @addod19 for your review, I have worked nav bar as required.

About the *Latest News Section* and *Featured Slideshows section* I am sorry there is no such section in the original page to clone. If there's one, please kindly leave me a screenshot.

The readme file live demo page seems to work very well on my end on the current feature branch: https://rawcdn.githack.com/rida-elbahtouri/-Bootstrap-project/86797a287a47ed33b08b2bdf224ea1f931e1331b/index.html
**other** than that I added  the navbar links and  the Date

2020-06-02 23:34 UTC, lucasmazo32 requested changes
# Changes required :wrench:

You are doing a great job so far, and the project is looking good. 

For the project to get approved, kindly implement the changes mentioned below.

### Happy coding! :computer:

## Lucas Mazo

2020-06-02 23:34 UTC, lucasmazo32 commented on index.html
> +    <nav class="navbar fixed-top red-back">
- [ ] Kindly fix the navbar for large screens. At least in my end, it has differences. I also notice that the link provided on the PR is from a previous commit, kindly update it.

Source | Clone
-- | --
![image](https://user-images.githubusercontent.com/57414789/83579681-8c8eb580-a4ff-11ea-9c20-3ac11492b8d8.png) | ![image](https://user-images.githubusercontent.com/57414789/83579702-987a7780-a4ff-11ea-82c9-0b195c23cbad.png)

2020-06-02 23:55 UTC, rida-elbahtouri commented
fixed the navbar and updated the link:
https://rawcdn.githack.com/rida-elbahtouri/-Bootstrap-project/7d49d470a04f470c86503638e75027c5a80f564a/index.html

2020-06-03 09:06 UTC, peterrobert commented
**pull request under review by peter robert**

2020-06-03 09:27 UTC, peterrobert requested changes
**CHANGES REQUIRED** :recycle: 
A very great project so far :clap: Very impressive work with implementing the changes required :+1: 

However, there is one minor change that you should do in order to have this project approved. Kindly do that one change and resubmit the project for review.

Feel free to reach me on slack on @peterrobert  if you need more clarification :smiley:

2020-06-03 09:27 UTC, peterrobert commented on index.html
> +            </div>
**[REQUIRED]** kindly fix the text in this block. It is below the image and hence difficult to read on mobile and medium view
![snapshot-1591175528832](https://user-images.githubusercontent.com/32361963/83619147-1b4d1200-a594-11ea-9efc-b32612e79811.jpg)

2020-06-03 12:12 UTC, peterrobert approved these changes
**APPROVED** :clap: :clap: 
Great and impressive work :1st_place_medal: You have done all the requested changes and hence i approve this project :+1:  :100: 

Remember to merge your branch and submit the project completion form :smiley: 
On to the next project. Happy coding :computer:

2020-06-03 12:33 UTC, merged